engines:
  govet:
    enabled: true
  golint:
    enabled: false
  gofmt:
    enabled: true

ratings:
  paths:
    - "**.go"

exclude_paths:
- documentation/
- definitions
- gh-pages
- samples
- scripts