project_name: kyverno-cli 
before:
  hooks:
    - go mod download
builds:
- id: kyverno
  main: cmd/cli/kubectl-kyverno/main.go
  binary: kyverno-cli
  env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
  goarm: [6, 7]
archives:
- id: kyverno-archive
  name_template: |-
    kyverno_{{ .Tag }}_{{ .Os }}_{{ .Arch -}}
    {{- with .Arm -}}
      {{- if (eq . "6") -}}hf
      {{- else -}}v{{- . -}}
      {{- end -}}
    {{- end -}}
  builds:
    - kyverno-cli
  replacements:
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files: ["LICENSE"]
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
release:
  prerelease: auto
