project_name: kyverno-cli 
before:
  hooks:
    - go mod download
builds:
- id: kyverno-cli
  main: cmd/cli/kubectl-kyverno/main.go
  binary: kyverno-cli
  env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
  goarm: [6, 7]
- id: kyverno
  main: cmd/kyverno/main.go
  binary: kyverno
  env:
  - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
- id: kyvernopre
  main: cmd/initContainer/main.go
  binary: kyvernopre
  env:
  - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
archives:
- id: kyverno-cli-archive
  name_template: |-
    kyverno-cli_{{ .Tag }}_{{ .Os }}_{{ .Arch -}}
    {{- with .Arm -}}
      {{- if (eq . "6") -}}hf
      {{- else -}}v{{- . -}}
      {{- end -}}
    {{- end -}}
  builds:
    - kyverno-cli
  replacements:
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files: ["LICENSE"]
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    # commit messages matching the regexp listed here will be removed from
    # the changelog
    exclude:
      - '^docs:'
      - typo
brews:
  - github:
      owner: nirmata
      name: homebrew-kyverno-cli
    goarm: 6
    ids:
    - kyverno-cli-archive
    homepage:  https://www.kyverno.io
    commit_author:
      name: kyverno
      email: kyverno@nirmata.com
scoop:
  bucket:
    owner: nirmata
    name: scoop-kyverno-cli
  homepage:  https://www.kyverno.io
  commit_author:
    name: kyverno
    email: kyverno@nirmata.com
dockers:
  - dockerfile: ./cmd/initContainer/Dockerfile
    skip_push: true
    binaries:
      - kyvernopre
    image_templates:
      - "nirmata/kyvernopre:v{{ .Major }}"
      - "nirmata/kyvernopre:v{{ .Major }}.{{ .Minor }}"
      - "nirmata/kyvernopre:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "nirmata/kyvernopre:{{ .Tag }}"
      - "nirmata/kyvernopre:latest"
  - dockerfile: ./cmd/kyverno/Dockerfile
    skip_push: true
    binaries:
      - kyverno
    image_templates:
      - "nirmata/kyverno:v{{ .Major }}"
      - "nirmata/kyverno:v{{ .Major }}.{{ .Minor }}"
      - "nirmata/kyverno:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "nirmata/kyverno:{{ .Tag }}"
      - "nirmata/kyverno:latest"