apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kyverno-cli
spec:
  version: {{ .TagName }}
  homepage: https://github.com/nirmata/kyverno
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/nirmata/kyverno/releases/download/{{ .TagName }}/kyverno-cli_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
      bin: kyverno-cli
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/nirmata/kyverno/releases/download/{{ .TagName }}/kyverno-cli_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
      bin: kyverno-cli
  shortDescription: The Kyverno Command Line Interface (CLI) is designed to validate policies and test the behavior of applying policies to resources before adding the policy to a cluster. It can be used as a kubectl plugin and as a standalone CLI.
  description: |
    Usage:
      kubectl kyverno-cli /path/to/policy1.yaml
      Read more documentation at: https://github.com/nirmata/kyverno/blob/master/documentation/kyverno-cli.md