title = "Kyverno"
baseURL = "https://kyverno.netlify.com"
disableKinds = ["sitemap", "taxonomy", "taxonomyTerm"]
pygmentsCodefences = true
pygmentsStyle = "monokai"
copyright = "Nirmata"

enableGitInfo = true

[markup.highlight]
style = "paraiso-dark"

[params]
description = "Kubernetes Native Policy Management"
detail= "Manage policies as Kubernetes resources. Validate, mutate, and generate configurations. Select resources based on labels and wildcards. View policy enforcement as events. Detect policy violations for existing resources."
sansseriffont = "Open Sans"
monospacefont = "Fira Mono"
fontawesomeversion = "5.6.3"
logo = "/Kyverno_Horizontal.png"
favicon = ""
repositoryUrl = "https://github.com/nirmata/kyverno"
contentDir = "/content/"

[params.logos]
navbar = "/Kyverno_Horizontal.png"
footer = "/Kyverno_Horizontal.png"
panel = "/Kyverno_Horizontal.png"

[[params.colors.extra]]
name = "slack-green"
hex = "#74cdb0"

[[params.colors.extra]]
name = "github-black"
hex = "#000000"

[[params.colors.extra]]
name = "twitter-blue"
hex = "#00aced"

[params.social.github]
name = "GitHub"
url  = "https://github.com/nirmata/kyverno"
icon = "fa fa-github"
color = "github-black"

[params.social.slack]
name = "Slack"
url = "https://kubernetes.slack.com/"
icon = "fa fa-slack"
color = "slack-green"

[params.social.twitter]
name = "Twitter"
url = "https://twitter.com/kyverno"
icon = "fa fa-twitter"
color = "twitter-blue"


[[params.fonts]]
name = "Open Sans"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Fira Mono"
sizes = [400]
type = "monospace"


[[menu.main]]
name = "Docs"
url = "/docs/home"
weight = 1

[[menu.main]]
name = "Nirmata"
url = "https://nirmata.com"
weight = 2

[[menu.main]]
name = "Resources"
url = "/docs/resources"
weight = 3

[[params.features]]
title = "Policy definitions as Kubernetes resources"

[[params.features]]
title = "Validate, mutate, or generate Kubernetes resources"


[[params.features]]
title = "Match resources using label selectors and wildcards"


[[params.features]]
title = "Mutate using overlays (like Kustomize) or JSON Patch"


[[params.features]]
title = "Validate using overlays and powerful conditionals"


[[params.features]]
title = "Generate default resources during namespace creation"


[[params.features]]
title = "Reporting of policy violations for existing resources"


[[params.features]]
title = "Kubernetes events for resource changes and policy enforcement"


[[params.features]]
title = "Test policy changes using kubectl"

