name: build
on:
  push:
    branches:
      - 'fix-1278'
  pull_request:
    branches:
      - 'fix-1278'

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: docker images build
        run: |
          make docker-build-all

      - name :  Create Kind Cluster and setup kustomize
        run: |
          make ci

      - name: e2e testing
        run: |
          echo ">>> Install Kyverno"
          cat ${GITHUB_WORKSPACE}/definitions/install.yaml
          echo "Cat debug"
          kubectl apply -f ${GITHUB_WORKSPACE}/definitions/install.yaml
          kubectl apply -f ${GITHUB_WORKSPACE}/definitions/github/rbac.yaml
          chmod a+x ${GITHUB_WORKSPACE}/scripts/verify-deployment.sh
          sleep 50
          echo ">>> Check kyverno"
          kubectl get pods -n kyverno
          ${GITHUB_WORKSPACE}/scripts/verify-deployment.sh -n kyverno  kyverno
          echo ">>> Run Kyverno e2e test"
          make test-e2e
