name: build
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name : binary build & kustomize
        run: |
          make ci
      -
        uses: docker/build-push-action@v1
        name: kyverno docker build and publish
        with:
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_PASSWORD }}
          repository: "nirmata/kyverno"
          tag_with_ref: true
          push: ${{ github.event.pull_request.head.sha }}
          path: cmd/kyverno/
          dockerfile: cmd/kyverno/Dockerfile

      -
        uses: docker/build-push-action@v1
        name: kyvernopre docker build and publish
        with:
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_PASSWORD }}
          repository: "nirmata/kyvernopre"
          tag_with_ref: true
          push: ${{ github.event.pull_request.head.sha }}
          path: cmd/initContainer/
          dockerfile: cmd/initContainer/Dockerfile

      - uses: engineerd/setup-kind@v0.1.0
        name: Create kind cluster

      - name: e2e testing
        run: |
          export KUBECONFIG="$(kind get kubeconfig-path)"
          kubectl get nodes
          echo ">>> delete KIND's default storageclass"
          kubectl delete storageclass standard || true
          echo ">>> deploy hostpath provisioner"
          kubectl apply -n kube-system -f ${GITHUB_WORKSPACE}/definitions/github/hostpath-provisioner.yaml
          echo ">>> run pod"
          kubectl apply -f ${GITHUB_WORKSPACE}/definitions/github/hostpath-provisioner-pod.yaml
          echo ">>> Install Kyverno"
          kubectl apply -f ${GITHUB_WORKSPACE}/definitions/install.yaml
          sleep 60
          echo ">>> Run Kyverno e2e test"
          make test-e2e







