name: build

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://evalsocket:${TOKEN}@github.com".insteadOf "https://github.com"
      -
        name: Unshallow
        run: git fetch --prune --unshallow
        
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      -
        name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      -
        name: Make Setup
        run: |
          go mod download
          go generate -v ./...

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
      -
        name: Make kyverno
        run: |
          make kyverno
      -
        name: Make kyverno CLI
        run: |
          make cli
      -
        name: Make kyverno init container
        run: |
          make initContainer
      
