name: prereleaser
on:
  push:
    tags:
      - '*'

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - uses: creekorful/goreportcard-action@v1.0
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name : binary build & kustomize
        run: |
          make kyverno
          make initContainer

      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2

      -
        uses: docker/build-push-action@v1
        name: kyverno docker build and publish
        with:
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_PASSWORD }}
          repository: "evalsocket/kyverno"
          push: true
          path: cmd/kyverno/
          dockerfile: cmd/kyverno/Dockerfile
          tags: ${{ steps.get_version.outputs.version }}

      -
        uses: docker/build-push-action@v1
        name: kyvernopre docker build and publish
        with:
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_PASSWORD }}
          repository: "evalsocket/kyvernopre"
          push: true
          path: cmd/initContainer/
          dockerfile: cmd/initContainer/Dockerfile
          tags: ${{ steps.get_version.outputs.version }}

      - uses: J12934/helm-gh-pages-action@master
        name: Run Helm Publish
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          charts-folder: charts

      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.38