name: releaser

on:
  push:
    tags:
      - v*
  

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - uses: creekorful/goreportcard-action@v1.0
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Log into Docker
        run: echo "${{ secrets.DOCKERIO_PASSWORD }}" | docker login  -u ${{ secrets.DOCKERIO_USERNAME }} --password-stdin
      - name: Push image
        run: |
          docker push nirmata/kyverno
          docker push nirmata/kyvernopre



