name: releaser

on:
  push:
    tags:
      - '*'

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Make kyvernopre
        run: |
          make initContainer
      -
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: "nirmata/kyvernopre"
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          dockerfile : cmd/initContainer/Dockerfile
          path: .
      -
        name: Make kyvernopre
        run: |
          make kyverno
      -
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: "nirmata/kyverno"
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          dockerfile : cmd/kyverno/Dockerfile
          path: .